---
title: "Homework 4 - BSTA 522"
author: "Matthew Hoctor"
date: "1/25/2022"
output:
  pdf_document:
    toc: yes
  html_document:
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(dplyr)
library(readxl)
# library(tidyverse)
# library(ggplot2)
# library(CarletonStats)
# library(pwr)
# library(BSDA)
# library(exact2x2)
# library(car)
# library(dvmisc)
# library(emmeans)
# library(gridExtra)
# library(DescTools)
# library(DiagrammeR)
# library(nlme)
# library(doBy)
# library(geepack)
# library(rje)
# library(ISLR2)
# library(psych)
# library(MASS)
# library(caret)  #required for confusionMatrix function
# library(rje)
```

# Part C

Chap 5: #2, #9 (use B=1000 and set.seed(1237) in all questions) 

## 5.2



## 5.9



# Part D

Why do we want to use set.seed(1237) in #9 above?

# Session Info

```{r}
sessionInfo()
```

# References

1. James G, Witten D, Hastie T, Tibshirani R. An Introduction to Statistical Learning: With Applications in R. 1st ed. 2013, Corr. 7th printing 2017 edition. Springer; 2013.
